name: Doxic

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    needs: build
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
